# Generated by Django 4.2.19 on 2025-02-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name_plural': 'LessonProgresses'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='usercontentaccess',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
