# Generated by Django 4.2.19 on 2025-03-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_content', '0002_alter_category_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='intro',
            field=models.TextField(blank=True, help_text='Introduction content that will be displayed as a reading lesson'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='objective',
            field=models.TextField(blank=True, help_text='Learning objective for this subcategory'),
        ),
    ]
